### ISSUE TITLE
Please provide materials remaining weeks too!

### ISSUE THREAD

**Issue by shakeabi** [NAU-ACM/ACM-ICPC-Preparation#16] opened 2018-08-17 10:58 UTC

**Comment by BedirT** [comment] 2018-08-17 11:29
Hi 👋 

**Sorry for inconvenience**, but due to my graduate school applications I am not and was not able to contribute as much, I summoned help from friends and reddit recently, I still will be active inspecting, but the speed is all up to the help I will receive from community. If not I can finish everything by February 2019, after my applications.

**Comment by shakeabi** [comment] 2018-08-17 13:12
Thank you for replying. You've got a great resource there. Thank you so
much for compiling and making it open.
Great work!!

Abishake.

**Comment by rajat123456** [comment] 2018-08-17 14:45
@shakeabi , most of the contents will be available before ICPC 2018, and complete set will be available by the end of this year :)

**Comment by shakeabi** [comment] 2019-04-27 15:10
Please provide materials for all the weeks. It's a great compilation but would be better if it's complete.

**Comment by dipu-bd** [comment] 2019-05-02 06:48
> Please provide materials for all the weeks. It's a great compilation but would be better if it's complete.

agree

**Comment by royayon** [comment] 2019-07-07 10:11
I can't find anything after Week 13...? Can anyone help me?

**Comment by shakeabi** [comment] 2019-11-03 07:54
@rajat123456 @BedirT Bump

**Comment by BedirT** [comment] 2020-08-19 07:53
Duplicate of #4

**Closed as completed by BedirT** 2020-08-19 07:53 UTC
